### PR TITLE
Fallback to original <C-a> and <C-x> functions

### PR DESCRIPTION
**Pull request by hgigas**

### CODE REVIEW

**Comment by RutaTang** [comment]
Hi, thank you for your PR!

But currently, I do not plan to add fallbacks. Since users can easily add **number template** to `templates` I have provided to do the same things as how the original `<C-a>` and `<C-x>` works.

However, if you find this function is very important for a certain use case, please feel free to open an issue to discuss it first and then we can think over to add such a function. In addition, if you feel comfortable, please do not  write in the way like `vim.v.count == 0 and 1 or vim.v.count`. Although it is very awesome, it might be hard for future contributors to understand.

Anyway, thank you very much for your PR.

**Comment by hgigas** [comment]
I invite you to put an example that **fully** replicates the original operation of `<C-a>` and `<C-x>` with a template. It's possible but not easy. I also don't understand the point of duplicating existing functionality.

`question and yes or no` is the lua ternary operator `question ? yes : no` isn't awesome, is basic.

**Comment by OmiChrome** [comment]
hey  , i want to USE `<leader>i` as ` <c-a> ` 
how? i just like this way

**Comment by RutaTang** [comment]
> I invite you to put an example that **fully** replicates the original operation of `<C-a>` and `<C-x>` with a template. It's possible but not easy. I also don't understand the point of duplicating existing functionality.
> 
> 
> 
> `question and yes or no` is the lua ternary operator `question ? yes : no` isn't awesome, is basic.

Thank you! I know it is ternary operator. But for people from other langs like me may feel it confusing since not all potential contributors might be lua expert. I just want to make code as simple and understandable as possible even for people who are new in lua.

And for the fallbacks, since I plan to enable users to customize the key mappings later, I do not want to let its functionality out of templates. However, I may consider to provide a fallback option later to enable user to either choose fallback or not.

**Comment by RutaTang** [comment]
> hey  , i want to USE `<leader>i` as ` <c-a> ` 
> 
> how? i just like this way

Currently,You can use vim key mapping to map Leader-i to C-a. I will enable customized key mapping later

**Comment by RutaTang** [comment]
And I do not accept PRs for now since the plug-in is still in its early stage.

If you found bugs or need enhancements, please open an issue first. We can then discuss there.

**Comment by hgigas** [comment]
> > I invite you to put an example that **fully** replicates the original operation of `<C-a>` and `<C-x>` with a template. It's possible but not easy. I also don't understand the point of duplicating existing functionality.
> > `question and yes or no` is the lua ternary operator `question ? yes : no` isn't awesome, is basic.
> 
> Thank you! I know it is ternary operator. But for people from other langs like me may feel it confusing since not all potential contributors might be lua expert. I just want to make code as simple and understandable as possible even for people who are new in lua.
> 
> And for the fallbacks, since I plan to enable users to customize the key mappings later, I do not want to let its functionality out of templates. However, I may consider to provide a fallback option later to enable user to either choose fallback or not.

I wasn't talking about you but about those people who come from other languages

**Pull request closed without merging**
